#line 1 "./templates/master.html"
#include "data/tmpl_master.h" 
#line 2 "./templates/master.html"
namespace defskin {
	#line 3 "./templates/master.html"
	struct Master :public cppcms::base_view
	#line 3 "./templates/master.html"
	{
	#line 3 "./templates/master.html"
		Data::Master &content;
	#line 3 "./templates/master.html"
		Master(std::ostream &_s,Data::Master &_content): cppcms::base_view(_s),content(_content)
	#line 3 "./templates/master.html"
		{
	#line 3 "./templates/master.html"
		}
		#line 4 "./templates/master.html"
		virtual void page_footer() {
			#line 4 "./templates/master.html"
			out()<<"Все права защищены";
		#line 4 "./templates/master.html"
		} // end of template page_footer
		#line 5 "./templates/master.html"
		virtual void page_main() {
			#line 26 "./templates/master.html"
			out()<<"\n"
				"<div class=\"row\">\n"
				"    <div class=\"col-lg-12\">\n"
				"        <div class=\"intro-message\">\n"
				"            <h1>TravelMate</h1>\n"
				"            <h3>Your personal Travel Mate</h3>\n"
				"            <hr class=\"intro-divider\">\n"
				"            <ul class=\"list-inline intro-social-buttons\">\n"
				"                <li>\n"
				"                    <a href=\"#\" id=\"btn-login\" class=\"btn btn-default btn-lg\"><i\n"
				"                            class=\"fa fa-twitter fa-fw\"></i> <span class=\"network-name\">LOGIN</span></a>\n"
				"                </li>\n"
				"                <li>\n"
				"                    <a href=\"news/\"\n"
				"                       class=\"btn btn-default btn-lg\"><i class=\"fa fa-github fa-fw\"></i> <span\n"
				"                            class=\"network-name\">LETS GO!</span></a>\n"
				"                </li>\n"
				"            </ul>\n"
				"        </div>\n"
				"    </div>\n"
				"</div>\n"
				"";
		#line 26 "./templates/master.html"
		} // end of template page_main
		#line 28 "./templates/master.html"
		virtual void page_left_sidebar() {
			#line 28 "./templates/master.html"
			out()<<"Левая панелька";
		#line 28 "./templates/master.html"
		} // end of template page_left_sidebar
		#line 29 "./templates/master.html"
		virtual void render() {
			#line 143 "./templates/master.html"
			out()<<"\n"
				"<!DOCTYPE html>\n"
				"<html lang=\"en\">\n"
				"\n"
				"<head>\n"
				"\n"
				"    <meta charset=\"utf-8\">\n"
				"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
				"    <meta name=\"description\" content=\"\">\n"
				"    <meta name=\"author\" content=\"\">\n"
				"\n"
				"    <title>TravelMate</title>\n"
				"\n"
				"    <!--<script type=\"text/javascript\" src=\"//cdn.jsdelivr.net/jquery/1/jquery.min.js\"></script>-->\n"
				"\n"
				"\n"
				"    <link rel=\"stylesheet\" type=\"text/css\" href=\"../static/css/style1.css\"/>\n"
				"    <meta charset=\"utf-8\">\n"
				"\n"
				"    <title>TravelMate</title>\n"
				"\n"
				"\n"
				"    <link href=\"../static/css/bootstrap.css\" rel=\"stylesheet\">\n"
				"\n"
				"\n"
				"    <!--//<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>-->\n"
				"\n"
				"    <script src=\"https://code.jquery.com/jquery-3.2.1.js\"></script>\n"
				"\n"
				"\n"
				"    <link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\" rel=\"stylesheet\">\n"
				"    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\n"
				"\n"
				"    <script src=\"../static/js/bootstrap-select.js\"></script>\n"
				"\n"
				"    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\n"
				"    <link rel=\"stylesheet\" href=\"../static/css/bootstrap-select.css\">\n"
				"\n"
				"    <link href=\"../static/css/style1.css?v=3\" rel=\"stylesheet\">\n"
				"    <link href=\"../static/css/loginform.css\" rel=\"stylesheet\">\n"
				"\n"
				"\n"
				"    <link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic\" rel=\"stylesheet\"\n"
				"          type=\"text/css\">\n"
				"\n"
				"    <script src=\"//cdn.jsdelivr.net/momentjs/latest/moment.min.js\"></script>\n"
				"    <link rel=\"stylesheet\" type=\"text/css\" href=\"//cdn.jsdelivr.net/bootstrap/3/css/bootstrap.css\"/>\n"
				"\n"
				"    <!-- Include Date Range Picker -->\n"
				"    <script type=\"text/javascript\" src=\"//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js\"></script>\n"
				"    <link rel=\"stylesheet\" type=\"text/css\" href=\"//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css\"/>\n"
				"    <script src=\"../static/js/myjs.js\"></script>\n"
				"</head>\n"
				"\n"
				"<body>\n"
				"\n"
				"<nav class=\"navbar navbar-default navbar-fixed-top topnav\" role=\"navigation\">\n"
				"    <div class=\"container topnav\">\n"
				"        <div class=\"navbar-header\">\n"
				"\n"
				"            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\n"
				"                    data-target=\"#bs-example-navbar-collapse-1\">\n"
				"                <span class=\"sr-only\">Toggle navigation</span>\n"
				"                <span class=\"icon-bar\"></span>\n"
				"                <span class=\"icon-bar\"></span>\n"
				"                <span class=\"icon-bar\"></span>\n"
				"            </button>\n"
				"            <a class=\"navbar-brand topnav\" href=\"#\">TravelMate</a>\n"
				"        </div>\n"
				"        <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n"
				"            <ul class=\"nav navbar-nav navbar-right\">\n"
				"                <li>\n"
				"                    <a href=\"#about\">About</a>\n"
				"                </li>\n"
				"                <li>\n"
				"                    <a href=\"#services\">Services</a>\n"
				"                </li>\n"
				"                <li>\n"
				"                    <a href=\"#contact\">Contact</a>\n"
				"                </li>\n"
				"            </ul>\n"
				"        </div>\n"
				"    </div>\n"
				"</nav>\n"
				"\n"
				"\n"
				"<div class=\"modal fade\" id=\"login\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\"\n"
				"     style=\"display: none;\">\n"
				"    <div class=\"modal-dialog\">\n"
				"        <div class=\"loginmodal-container\">\n"
				"            <h1>Login to Your Account</h1><br>\n"
				"            <form name=\"login\" method=\"post\" action=\"/login\">\n"
				"                <input type=\"text\" name=\"user\" placeholder=\"Username\">\n"
				"                <input type=\"password\" name=\"pass\" placeholder=\"Password\">\n"
				"                <input type=\"submit\" name=\"login\" class=\"login loginmodal-submit\" value=\"Login\">\n"
				"            </form>\n"
				"            <div class=\"login-help\">\n"
				"                <a id=\"register\" href=\"#\">Register</a> - <a href=\"#\">Forgot Password</a>\n"
				"            </div>\n"
				"            <div id=\"signup\" style=\"display:none\"><br>\n"
				"                <form name=\"signup\" method=\"post\" action=\"/signup\">\n"
				"                    <input type=\"email\" name=\"email\" placeholder=\"email\">\n"
				"                    <input type=\"password\" name=\"pass\" placeholder=\"password\">\n"
				"                    <input type=\"submit\" name=\"login\" class=\"login loginmodal-submit btn btn-lg btn-success\" value=\"SignUp\">\n"
				"                </form>\n"
				"            </div>\n"
				"        </div>\n"
				"    </div>\n"
				"</div>\n"
				"\n"
				"<a name=\"about\"></a>\n"
				"<div class=\"intro-header\">\n"
				"    <div class=\"container\">\n"
				"\n"
				"        ";
			#line 143 "./templates/master.html"
			page_main();
			#line 149 "./templates/master.html"
			out()<<"\n"
				"\n"
				"    </div>\n"
				"</div>\n"
				"</body>\n"
				"</html>\n"
				"";
		#line 149 "./templates/master.html"
		} // end of template render
	#line 150 "./templates/master.html"
	}; // end of class Master
#line 151 "./templates/master.html"
} // end of namespace defskin
#line 1 "./templates/news.html"
#include "data/tmpl_news.h" 
#line 2 "./templates/news.html"
namespace defskin {
	#line 3 "./templates/news.html"
	struct News :public Master
	#line 3 "./templates/news.html"
	{
	#line 3 "./templates/news.html"
		Data::News &content;
	#line 3 "./templates/news.html"
		News(std::ostream &_s,Data::News &_content): Master(_s,_content),content(_content)
	#line 3 "./templates/news.html"
		{
	#line 3 "./templates/news.html"
		}
		#line 4 "./templates/news.html"
		virtual void page_main() {
			#line 50 "./templates/news.html"
			out()<<"\n"
				"<div class=\"container-fluid\">\n"
				"    <form class=\"form-horizontal\" role=\"form\">\n"
				"        <div class=\"form-group form-group-lg\">\n"
				"            <div class=\"col-md-3 col-md-offset-2\">\n"
				"                <select id=\"basic\" class=\"selectpicker form-control\" data-live-search=\"true\"\n"
				"                        title=\"Куда...\">\n"
				"                    <optgroup label=\"Russia\">\n"
				"                        <option>Moscow</option>\n"
				"                        <option>Ryazan</option>\n"
				"                        <option>Saint-Petersburg</option>\n"
				"                        <option>Tula</option>\n"
				"                    </optgroup>\n"
				"                    <optgroup label=\"USA\">\n"
				"                        <option>New York</option>\n"
				"                        <option>Orlando</option>\n"
				"                        <option>Chicago</option>\n"
				"                        <option>Los Angeles</option>\n"
				"                    </optgroup>\n"
				"                </select>\n"
				"            </div>\n"
				"            <div class=\"col-md-3\">\n"
				"                <div class=\"input-group date\">\n"
				"                    <input id='datetimepicker3' type=\"text\" class=\"form-control\" placeholder=\"Когда...\"/>\n"
				"                    <span class=\"input-group-addon\">\n"
				"      <span class=\"glyphicon glyphicon-calendar\"></span>\n"
				"    </span>\n"
				"                </div>\n"
				"            </div>\n"
				"            <div class=\"col-md-2\">\n"
				"                <button class=\"btn btn-danger btn-lg form-control\">Lets Go</button>\n"
				"            </div>\n"
				"        </div>\n"
				"    </form>\n"
				"</div>\n"
				"<script>\n"
				"    $(function () {\n"
				"        $('#datetimepicker3').daterangepicker({\n"
				"            //\"singleDatePicker\": true,\n"
				"            \"autoUpdateInput\": false\n"
				"        });\n"
				"    });\n"
				"    $('#datetimepicker3').on('apply.daterangepicker', function (ev, picker) {\n"
				"        $(this).val(picker.startDate.format('MM.DD.YYYY'));\n"
				"    });\n"
				"</script>\n"
				"";
		#line 50 "./templates/news.html"
		} // end of template page_main
	#line 51 "./templates/news.html"
	}; // end of class News
#line 52 "./templates/news.html"
} // end of namespace defskin
#line 53 "./templates/news.html"
namespace {
#line 53 "./templates/news.html"
 cppcms::views::generator my_generator; 
#line 53 "./templates/news.html"
 struct loader { 
#line 53 "./templates/news.html"
  loader() { 
#line 53 "./templates/news.html"
   my_generator.name("defskin");
#line 53 "./templates/news.html"
   my_generator.add_view<defskin::Master,Data::Master>("Master",true);
#line 53 "./templates/news.html"
   my_generator.add_view<defskin::News,Data::News>("News",true);
#line 53 "./templates/news.html"
    cppcms::views::pool::instance().add(my_generator);
#line 53 "./templates/news.html"
 }
#line 53 "./templates/news.html"
 ~loader() {  cppcms::views::pool::instance().remove(my_generator); }
#line 53 "./templates/news.html"
} a_loader;
#line 53 "./templates/news.html"
} // anon 
